# Site settings
title: Braze Documentation
email: success@braze.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to Braze Documentation. Braze provides a comprehensive user engagement solution for your mobile apps.
baseurl: "/docs/ja" # the subpath of your site, e.g., /blog
homeurl: "https://www.braze.com" # the base hostname & protocol for your site, e.g., http://example.com
twitter_username: Braze
github_username:  braze-inc

language: ja

destination: _site/docs/ja

# Source dir
source: '.'

lab_index_name: "DocSearch_Japanese"

# Allows the DocSearch element to be inspected. Set to true locally, but don't
# check in in that state, or it will cause undesirable behavior in prod.
search_debug: false

# For local testing, set to false to increase build time by not pulling partner api
# and markdown data. MAKE SURE TO TURN BACK ON PRIOR TO COMMIT.
partner_api: true
markdown_api: true

# GitHub config
github_baseurl: 'https://github.com/braze-inc/braze-docs/blob/develop/_lang/ja/'

# Collections directory
collections_dir: _lang/ja/


collections:
  home:
    title: ドキュメンテーション
  user_guide:
    title: ユーザーガイド
  developer_guide:
    title: 開発者ガイド
  api:
    title: API
    default_nav_url: basics/
  partners:
    title: テクノロジーパートナー
  help:
    title: ヘルプ
  hidden: # Hidden pages not directly linked via navigation
    title: Braze
  docs_pages: # Site specific pages. ie main redirects and search
    title: Braze


# Image asset pipeline setting for japr
asset_pipeline:
  display_path: docs/ja/assets

# Algolia Search index
algolia:
  index_name: "DocSearch_Japan"
  files_to_exclude:
    - _lang/ja/_hidden/*
    - _lang/ja/_hidden/*/* #exclude hidden subdirectories from indexing
    - _lang/ja/_hidden/*/*/* #exclude additional hidden subdirectories from indexing
    - _lang/ja/_docs_pages/*
    - _lang/ja/_docs_pages/*/* #exclude hidden subdirectories from indexing
    - _lang/ja/_docs_pages/*/*/* #exclude additional hidden subdirectories from indexing
    - _lang/ja/_home/Styling_Test_Page.md
